[project]
name = "youtube-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.11.8",
    "streamlit>=1.45.0",
    "yt-dlp>=2025.4.30",
]
